import "./globals.css";
import type { Metadata } from "next";
import LocalFont from "next/font/local";
import SessionProvider from "@/app/context/SessionProvider";

const inter = LocalFont({
  src: "../../fonts/Inter.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  );
}
